FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install && npm install -g serve
COPY . .
RUN npm run build
EXPOSE 4200
CMD ["serve", "-s", "dist/inventory-frontend/browser", "-l", "4200"]
